name: chatbot-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # Conda-specific packages (compiled/non-PyPI)
  - faiss-cpu=1.7.2
  - numpy=1.26.4
  - pip
  - pip:
    # PyPI packages (your actual dependencies)
    - flask==3.0.3
    - flask-cors==5.0.1
    - langchain==0.2.1
    - langchain-community==0.2.1
    - langchain-core==0.2.4
    - openai==1.68.2
    - pypdf==5.4.0
    - python-dotenv==1.0.1